// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
   tutorialSidebar: [
    {
      type: 'category',
      label: 'Présentation',
      collapsed: false,
      items: [
        'presentation/introduction',
        'presentation/bts-sio',
        'presentation/campus-ermitage',
        'presentation/syadem',
      ],
    },
    {
      type: 'category',
      label: 'Parcours & compétences',
      collapsed: false,
      items: [
        'parcours/etudes',
        'parcours/travail',
        'parcours/competences',
        'parcours/certifications',
      ],
    },
    {
      type: 'category',
      label: 'Réalisations',
      collapsed: false,
      items: [
        'realisations/e5-e6',
        'realisations/projet1',
        'realisations/projet2',
      ],
    },
  ],
};

export default sidebars;
